### PR TITLE
Chore/add support for tagging

### PR DESCRIPTION
**Pull request by donnapep**
* Add support for tagging. If one or more `<rise-tag>` child elements are found, then a request is made to the Storage Tagging API. Otherwise, Google Storage API is called to get the list of files. In both cases, a JSON response is returned.
* Add tests for tagging.
* Split test coverage across multiple HTML files.
* Update demo.
* Version bump to 1.0.0 as this is a major release with breaking changes.
* Update bower and npm packages.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees This is the bulk of the work for tagging. There is some additional functionality to come, but I thought it might be easier to do the review in chunks within the same PR. Please review. Thx.

**Comment by stulees** [comment]
@donnapep Great test coverage and like the separation of tests! I noticed the `rise-tag.html` doesn't import a separated `-data.js` file like how you import `rise-storage-data.js` in the other test files. Any reason? Otherwise :+1:

**Comment by donnapep** [comment]
@stulees Thanks. Re: why tagging tests don't import `rise-storage-data.js`: it's because the data that comes back from the tagging API is in a different format, so it uses a different set of data. I expect that I may need to create a `rise-tag-data.js` as I add more tests for tagging.

**Comment by donnapep** [comment]
@stulees Added support for sorting tagged files. Please review. Thx.

**Comment by donnapep** [comment]
@stulees Added another commit for refreshing tagged files. Thx.

**Comment by stulees** [comment]
@donnapep Looks good on both :+1:

**Comment by donnapep** [comment]
* Moved tests for invalid attributes on `<rise-storage>` and `<rise-tag>` to their own files and added additional tests.
* Fixed a couple of issues in the component as a result of running these tests.
* Created new file for storing tagged files data.

@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@stulees The reason the automated tests weren't running was because web-component-tester couldn't locate some of the files. I've had to update the locations of the external files and now the tests run automatically on my local machine. I found [this article](http://code.tutsplus.com/tutorials/sharing-polymer-components-part-1--cms-21264) that helped to clear things up for me.

I'm working on getting CCI to run them as well, but I think this is going to take a fair bit of tinkering so I thought I'd have you review now and then I'll squash everything and start fresh. Thx.

**Comment by stulees** [comment]
@donnapep Okay thanks for clarifying :+1:

**Comment by donnapep** [comment]
@stulees Updated the ReadMe. Please review.

Also, I can't get the tests to pass on CircleCI as `web-component-tester` expects Chrome version >= 39.0.2171.0 and CCI is running Chrome 38.0.2125.122. Downgrading the version of `wct` also doesn't help. This should resolve itself once CCI updates Chrome.

**Comment by stulees** [comment]
@donnapep :+1:  Do you know when CCI plans to update its Chrome version?

**Comment by donnapep** [comment]
@stulees No, but the last time they updated was in October.

**Comment by donnapep** [comment]
@stulees Please review. This is the final change for tagging. Thx.

**Comment by donnapep** [comment]
@stulees Also, on CircleCI there's a notification that says they're doing a container update tomorrow. Chrome is not included in that update, but they will be upgrading it in the next container update which is currently slated for the following week. I'll be able to pick the automated tests back up after that.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
