### PR TITLE
Add file name in response

### PR DESCRIPTION
**Pull request by fjvallarino**
This PR fixes and tests that file name is always included in the response.

@stulees @donnapep @tejohnso please review

### CODE REVIEW

**Comment by stulees** [comment]
@fjvallarino Curious, what made you decide to provide a second demo? Otherwise, :+1:

**Comment by fjvallarino** [comment]
@stulees It was suggested by @mmeiers

**Comment by stulees** [comment]
@fjvallarino They're so similar I'm wondering if you're new `demo-static.html` can suffice. @donnapep Thoughts?

**Comment by donnapep** [comment]
Since it's already there, I don't think it hurts to leave it in.

**Comment by fjvallarino** [comment]
@donnapep Is the PR good to go for you? 

@donnapep @stulees For future PRs, should I wait for approval from both of you or is one good enough? Thanks!

@tejohnso FYI

**Comment by mmeiers** [comment]
:+1: Thanks @fjvallarino

**Comment by donnapep** [comment]
@fjvallarino I think one of us reviewing is fine. Thx. :+1:

**Pull request merged**
