### PR TITLE
Remove tagging functionality

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees As discussed, please remove the first commit for removing tagging. I wouldn't bother reviewing the second as it's all going to change. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@stulees The second last commit completely refactors the component such that:

* If Rise Cache is running, the component checks in with Rise Cache to see if the `Last Modified` header of any of the files have changed. If so, `rise-storage-response` is fired. Rise Cache takes care of communicating with the Storage API.
* If Rise Cache is not running, it's the component's responsibility to check with the Storage API to see if files have changed by inspecting the `etag` property.

Also, I've refactored the tests (again). Now they are separated into e2e and unit tests.

The last commit fixed some build errors.

Please review. Sorry it's so long. I should have tried to implement this in a more piecemeal fashion.

Thx.

**Comment by stulees** [comment]
@donnapep Nice :+1:

**Pull request merged**
