### PR TITLE
Lift restriction on only refreshing folders

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep In the tests you lift the restriction but in `rise-storage-refresh.html` there is only one instance of `rise-storage` with a `folder` value that gets tested. There's no instance of `rise-storage` with just a `fileName` value to test the refresh. Should there be one? Thanks

**Comment by donnapep** [comment]
@stulees I decided not to. I didn't see the point since it tests the exact same piece of code.

**Comment by stulees** [comment]
@donnapep Understandable. Can you clarify for me then if an instance created with a folder value, eg.
```
<rise-storage companyId="abc123" folder="my-folder" refresh="10"></rise-storage>
```
executes the same flow of code as an instance with only a file name value, eg.
```
<rise-storage id="folder" companyId="abc123" folder="" fileName="image.jpg" refresh="10"></rise-storage>
```
If not, then I would say it warrants a refresh test for a `fileName` scenario. Otherwise, :+1:  Thanks

**Comment by donnapep** [comment]
@stulees That's correct. Both folder and file share the same code path as far as refreshing is concerned. Tagging, on the other hand, has a different flow, and so I have separate tests for that. Thx.

**Pull request merged**
