### PR TITLE
Only count files when computing total items count

### PR DESCRIPTION
**Pull request by fjvallarino**
@donnapep @stulees @tejohnso please review

### CODE REVIEW

**Comment by donnapep** [comment]
@fjvallarino Can we leave the version as is for bug fixes? I think we only need to bump it if there's a breaking change.

Also, should there be a test for this?

Thx!

**Comment by fjvallarino** [comment]
@donnapep Updated

**Comment by donnapep** [comment]
@fjvallarino You rock, thanks!

**Comment by stulees** [comment]
@fjvallarino :+1:

**Pull request merged**
