### PR TITLE
Added storage subscription status check

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Created unit tests

@stulees I think the only thing missing is the integration tests. Thanks for taking a look at it. 

cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi I've fixed the integration tests, please review the last commit. Unfortunately CCI seems to be experiencing queue issues - https://circleci.statuspage.io/ so no confirmation of the tests passing on CCI yet. I know they pass locally. Hopefully this will be cleared soon and the build will have ran for when you review this. Thanks

**Comment by stulees** [comment]
@rodrigopavezi CCI back to normal, tests passed.

**Comment by rodrigopavezi** [comment]
@stulees awesome. thanks a mill. I will add some integration tests for the subscription status. cheers

**Comment by rodrigopavezi** [comment]
@stulees test added, please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good :+1:

**Pull request merged**
