### PR TITLE
Use selfLink for Storage URL

### PR DESCRIPTION
**Pull request by donnapep**
* Use `selfLink` instead of `mediaLink` for Storage URL.
* Remove console messages about no company ID.
* Update `circle.yml` to get automated tests to run.
* Add instructions on how to get Company ID to ReadMe.
* Use more realistic URLs in tests.
* Version bump.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1:  What exactly are the changes to `circle.yml` doing to enable automated tests to run? Just want to get a better understanding.

**Comment by donnapep** [comment]
@stulees It's installed Chrome stable since CCI is on an older version that isn't supported.

**Comment by stulees** [comment]
@donnapep Okay thanks

**Pull request merged**
